
package selfDrivenCars;

import simView.*;
import java.awt.*;

public class SelfDrivingSystem extends  ViewableDigraph{

public SelfDrivingSystem(){
super("Self Driving System");

addInport("in");
addOutport("stop car");
addOutport("Go");
addOutport("open air bag");

ViewableAtomic pedG = new PedestrianGenerator("Pedestrian Generator",12);
add(pedG);
ViewableAtomic senG = new SensorDataGenerator("Sensor Data Generator",40);
add(senG);
ViewableAtomic intelSys = new ControlSystem("Control System",20);
add(intelSys);
ViewableAtomic obstacle = new Obstacles("Obstacle Generator",50);
add(obstacle);

ViewableAtomic junction = new Junction("Junction",500);
add(junction);

ViewableAtomic collisionObserver = new CollisionObserver("Collision Observer", 20);
add(collisionObserver);



addCoupling(senG,"out",intelSys,"sensorDataIn");

addCoupling(pedG,"out",junction,"ariv");
addCoupling(pedG,"out",senG,"pedestrianSenseIn");
addCoupling(obstacle,"out",senG,"obstacleSenseIn");
addCoupling(senG, "out", junction, "sensorWatchIn");
addCoupling(intelSys,"brake",this,"stop car");
addCoupling(intelSys,"accelerate",this,"Go");
addCoupling(intelSys,"air bag",this,"open air bag");
addCoupling(senG, "out1", collisionObserver, "in");
addCoupling(collisionObserver, "out", intelSys, "sensorDataIn");

}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1248, 562);
        if((ViewableComponent)withName("Pedestrian Generator")!=null)
             ((ViewableComponent)withName("Pedestrian Generator")).setPreferredLocation(new Point(130, 364));
        if((ViewableComponent)withName("Sensor Data Generator")!=null)
             ((ViewableComponent)withName("Sensor Data Generator")).setPreferredLocation(new Point(290, 244));
        if((ViewableComponent)withName("Junction")!=null)
             ((ViewableComponent)withName("Junction")).setPreferredLocation(new Point(375, 38));
        if((ViewableComponent)withName("Collision Observer")!=null)
             ((ViewableComponent)withName("Collision Observer")).setPreferredLocation(new Point(648, 325));
        if((ViewableComponent)withName("Control System")!=null)
             ((ViewableComponent)withName("Control System")).setPreferredLocation(new Point(787, 245));
        if((ViewableComponent)withName("Obstacle Generator")!=null)
             ((ViewableComponent)withName("Obstacle Generator")).setPreferredLocation(new Point(118, 126));
    }
}
